# Generated by Django 3.2 on 2021-04-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
